Server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone5703?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: capstone5703
